#!/bin/bash

set -o errexit

pipenv run test
{% if cookiecutter.docs != 'y' %}# {% endif %}pipenv run doctest
{% if cookiecutter.docs != 'y' %}# {% endif %}pipenv run build-docs

echo -e "\033[1;32m  Tests passed  \033[1;m"
